update rpki.texi
rtrlib/frr-1 pull request #2
Opened 2017-10-26 14:15 UTC by colinbs

The RPKI documentation for the FRR integration needs some work.

2017-10-27 08:22 UTC, smlng requested changes

2017-10-27 08:22 UTC, smlng commented on doc/rpki.texi
> +@c This is part of the FRRouting Manual.
in `bgpd.texi` this line is `@c This is part of the Frr Manual.` and in `babeld.texi` its `@c This is part of the FRR Manual.`, so inconsistent as it is, I would go for the latter version with `FRR Manual`, or not?

2017-10-27 08:22 UTC, smlng commented on doc/rpki.texi
> +Origin Validation in FRRouting implements both RFCs.
looking through other docs its mostly referred to as plain and short `FRR` not `FRRouting`

2017-10-27 08:22 UTC, smlng commented on doc/rpki.texi
> +validation. You need to configure at least one reachable cache server (see next section).
add link to that section instead or additionally.

2017-11-07 09:32 UTC, smlng approved these changes

2017-11-07 09:33 UTC, smlng commented
@colinbs changes look good to me, clear to merge - or are you still editing?

2017-11-08 10:10 UTC, colinbs commented
Feel free to merge away : )

2017-11-08 10:19 UTC, merged